# Generated by Django 2.2.7 on 2020-01-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
